server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO

spring:
  # Thymeleaf propertis
  thymeleaf:
    cache: false
  # Datasource properties
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_mgmt_db
    username: postgres
    password: postgres
  # JPA and Hibernate properties
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  # JavaMail Configuration
  mail:
    host: smtp.gmail.com
    username: deutschmankote@gmail.com
    password: 131_KOte**
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

# OAuth2 Providers Config
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

# admin user configuration
app:
  user:
    admin:
      email: admin@admin123
      password: admin123